#! /bin/bash

# to be replaced

cd /home/pi/git/SendGMail

echo Compiling java files...

javac  -classpath /home/pi/git/SendGMail/lib/'*' */*.java

echo Creating jar file...

jar cvfe SendGMail.jar sendmail/SendGMail */*.class

echo Jar file in /home/pi/git/SendGMail
echo
ls -l /home/pi/git/SendGMail/SendGMail.jar
echo
